### ISSUE TITLE
Mounting Longhorn volumes results in failure

### ISSUE THREAD

**Issue by hananmoiseyev** [kvdi/kvdi#31]
We use Longhorn as our storage solution in the cluster. This thing is sometimes taking time to bind, and the result is usually a POD that states that the mount fails. Maybe a longer timeout is required?

**Comment by tinyzimmer** [comment]
That would not be something kvdi has control over. It's very possible longhorn is just not suited for the usage. Or there may be things you are able to configure in longhorn to make it behave better.

The only thing `kvdi` **could** do that is somewhat related to this, is change the `chown` behavior on pod mounts. And I already plan on doing that anyway. But to be clear, it is not related to this, because longhorn is even mounting the volume.

I do feel compelled to remind you this project is **very** experimental and you should not expecting enterprise grade features out of it by any stretch.
